### ISSUE TITLE
Log more of Input Events Level 2 data

### ISSUE THREAD

**Issue by danburzo** [danburzo/input-methods#24]
* DataTransfer
* range

**Comment by ianstormtaylor** [comment]
It would be awesome if the events were logged to the console along with their # so that you could open up the objects and look through them right there in the inspector.

**Comment by danburzo** [comment]
Fixed a few aspects of this in the new version at: https://danburzo.ro/ui-events-viewer/ . Specifically:

* Show the list of MIME types available in `InputEvent.dataTransfer`
* Log the event along with its index number to the console as well.
