### ISSUE TITLE
Is there a reasonable way to hook this up directly to either SlateJS or component elements of SlateJS?

### ISSUE THREAD

**Issue by Slapbox** [danburzo/input-methods#26]
I've been looking at how to deal with composition events for a few days now and this seems to be far and away the most useful logger. Great work!

Is there some reasonable way to integrate your tool into an example like this? https://optimdata.github.io/slate/#/mobile

Thanks very much!

**Comment by danburzo** [comment]
Hmm, I haven't touched this code in almost a year, I'll have to poke around a bit and see if we can do something about it :)

**Comment by Slapbox** [comment]
Thanks @danburzo 

If you can give me any pointers after you find some time to poke around, I'd really appreciate it. This is a really phenomenal tool and gives me some hope for figuring out how to get Slate working on mobile.

**Comment by danburzo** [comment]
There's a new, vanilla JS version here: https://danburzo.ro/ui-events-viewer/ The source code is inlined in the HTML (there's not much to it). Since this issue is already five years old, it seems unlikely that I'll ever get to implementing a pluggable component for it 😅
